[phases.setup]
nixPkgs = ['nodejs-22_x', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'

[providers.apt]
packages = [
  'build-essential',
  'libcairo2-dev',
  'libpango1.0-dev',
  'libjpeg-dev',
  'libgif-dev',
  'librsvg2-dev',
  'libpixman-1-dev',
  'pkg-config',
  'python3'
]

